### ISSUE TITLE
.NET 5

### ISSUE THREAD

**Issue by hn1** [dncuug/X.PagedList#199]
The control throws all sorts of errors when used with the newest release of .NET Core the .NET 5.
Any idea when a new version compatible with .NET 5 will be released?
Thanks

**Comment by sashapvt** [comment]
Could you please provide some examples of errors you got?

I switched `X.PagedList.Mvc.Example.Core` project Target framework from .Net Core 3.1 to .Net 5.0. And it builds and runs normally.

![image](https://user-images.githubusercontent.com/22121741/99909920-eaa09680-2cf3-11eb-9e2d-9f438d350e38.png)

![image](https://user-images.githubusercontent.com/22121741/99909944-0441de00-2cf4-11eb-8f09-fcce03543f66.png)

**Comment by MCFHTAGENTS** [comment]
I am seeing the following:
```
System.InvalidOperationException: Unable to translate collection subquery in projection since the parent query doesn't project key columns of all of it's tables which are required to generate results on client side. This can happen when trying to correlate on keyless entity or when using 'Distinct' or 'GroupBy' operations without projecting all of the key columns.
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.ApplyCollectionJoin(Int32 collectionIndex, Int32 collectionId, Expression innerShaper, INavigationBase navigation, Type elementType, Boolean splitQuery)
   at Microsoft.EntityFrameworkCore.Query.Internal.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.Internal.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.Internal.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.Internal.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.Internal.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPostprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at X.PagedList.PagedList`1..ctor(IQueryable`1 superset, Int32 pageNumber, Int32 pageSize)
   at X.PagedList.PagedList`1..ctor(IEnumerable`1 superset, Int32 pageNumber, Int32 pageSize)
   at X.PagedList.PagedListExtensions.ToPagedList[T](IEnumerable`1 superset, Int32 pageNumber, Int32 pageSize)
   at MyController.Index(String filter, String searchTerm, Nullable`1 source, String sourceName, Nullable`1 page, String sortBy, String bookingType, Nullable`1 from, Nullable`1 to) in xxxx
   at lambda_method4025(Closure , Object , Object[] )
```

The ToPagedList method is being called on a this.context.MyDerivedView

which is itself coming from 
           builder.Entity<MyDerivedView>(eb =>
            {
                eb.HasNoKey();
                eb.ToView("VW_BOOKINGS_DERIVED", "CORE");
                eb.Property(v => v.BookingId).HasColumnName("BOOKING_ID");

and has no key by design.

Thanks
Mark

**Comment by sashapvt** [comment]
Hi Mark,

The exception actually may throws in this constructor when trying to evaluate `IQueryable<T> superset` you provided:

```
		public PagedList(IQueryable<T> superset, int pageNumber, int pageSize)
			: base(pageNumber, pageSize, superset?.Count() ?? 0)
		{
			if (TotalItemCount > 0)
			{
				Subset.AddRange(pageNumber == 1
					? superset.Take(pageSize).ToList()
					: superset.Skip((pageNumber - 1) * pageSize).Take(pageSize).ToList()
				);
			}
		}
```

It seems like there is some problem in the input expression. Could you try to implicitly evaluate the expression before you provide it into the `ToPagedList` method? For example:
```
var collection = myQuery.ToList();
collection.ToPagedList<T>(1, 1);
```

**Comment by ernado-x** [comment]
New version was published: https://github.com/dncuug/X.PagedList/releases/tag/v8.1

.NET Framework support  was dropped.
